import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useForm } from 'react-hook-form';

export default function Home() {
  const { register, handleSubmit, formState: { errors } } = useForm();
  const onSubmit = () => alert("Thank you ");
  console.log(errors);
  
  return (
    <div>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.form_container}>
          <div className={styles.form_heading}>
          Join 1000 people who took the 
          free introduction in the last week
          </div>

          <div className={styles.form_start}>
            <form className={styles.form_elements} >
              <label className={styles.label_ele}> Name*</label>
              <input className={styles.form_input} type="text" {...register("Name", {required: true})} />

              <label className={styles.label_ele}>Email*</label>
              <input className={styles.form_input} type="email" {...register("Email", {required: true, pattern: /^\S+@\S+$/i})} />

              <label className={styles.label_ele}>Phone*</label>
              <input className={styles.form_input} type="tel" {...register("Phone", {required: true, maxLength: 12})} />

              <label className={styles.label_ele}>Select Day</label>
              <select className={styles.form_input} {...register}>
                <option>Today</option>
                <option>Tomorrow</option>
                <option>Other</option>
              </select>


              <label className={styles.label_ele}>Select Time</label>
              <select className={styles.form_input} {...register}>
                <option value="9am">9am</option>
                <option value="11am">11am</option>
                <option value="3pm">3pm</option>
                <option value="5pm">5pm</option>
                <option value="7pm">7pm</option>
              </select>
              <label>Have you learnt Sudarshan Kriya*</label>
              <div className={styles.form_que}>
              <input {...register("Have you learnt Sudarshan Kriya*", { required: true })} type="radio" value="Yes" />
              <label>Yes</label>
              <input {...register("Have you learnt Sudarshan Kriya*", { required: true })} type="radio" value="No" />
              <label>No</label>
              </div>
            </form>
          </div>


          <div>
            <button className={styles.button_form} type="submit" onClick={handleSubmit(onSubmit)}>Sign up for the introductory talk now</button>
          </div>

          <div className={styles.form_footer}>
            <div>
            By registering for the workshop, 
            you’ll get a Whatsapp and Email invite 
            with further instructions. 
            </div>
          <br></br>
           We’ll never share your information with anybody. 
          See our privacy policy.
          </div>
        </div>
      </div>
    </div>
  )
}
